${NODE_LABEL}

def pfInit(setMainAgent) {
    def _pf
    // restrict pf.init() under ".pf-framework", to mitigate PF_PATH finding cost
    def frameworkExists = fileExists ".pf-framework/rtk_stages.groovy"
    def configExists = fileExists ".pf-framework/**/global_config.json"

    if (frameworkExists == true && configExists == true) {
        dir (".pf-framework") {
            print "Jenkinsfile.restartable starts at the same agent"
            _pf = load "rtk_stages.groovy"
            _pf.init()
        }
    }
    else {
        // Jenkinsfile.restartable does not start at the same agent
        dir (".pf-framework") {
            deleteDir()
            if (isUnix() == true) {
                unstash name: "pf-framework"
            }
            else {
                if (env.PF_DEBUG_RESTARTABLE) {
                    bat """
                        set GIT_SSL_NO_VERIFY=true && git clone ${PF_FRAMEWORK_URL}/gerrit/sdlc/jenkins-pipeline --depth 1 -b ${PF_FRAMEWORK_DEV_BRANCH} .
                    """
                }
                else {
                    bat """
                        set GIT_SSL_NO_VERIFY=true && git clone ${PF_FRAMEWORK_URL}/gerrit/sdlc/jenkins-pipeline --depth 1 -b ${PF_FRAMEWORK_PROD_BRANCH} .
                    """
                }
            }

            try {
                unstash name: "pf-config"
            }
            catch (e) {
                // exception caused by Old-fashion Jenkinsfile.appetizer
                print "Old-fashion Jenkinsfile.appetizer"
                dir (".pf-config") {
                    deleteDir()
                checkout scm
                stash name: "pf-config", includes: "**"
                }
                unstash name: "pf-config"
            }

            _pf = load "rtk_stages.groovy"
            _pf.init()
        }
    }

    if (setMainAgent == true) {
        env.PF_MAIN_AGENT = env.NODE_NAME
    }
    //_pf.pascCleanWs()
}

def unstashPipelineFramework() {
    print "Unstash PF under " + pwd()
    // unstash to PF_ROOT
    env.PF_ROOT = ".pf-all"
    print "env.PF_ROOT ${env.PF_ROOT}"
    dir (WORKSPACE) {
        dir (env.PF_ROOT) {
            deleteDir()
            // WORKAROUND (windows virus issue ITSDLC-779)
            // windows agent would be disconnected after unstash "stash-pf-framework"
            // call git clone to avoid this issue
            // git clone jenkins-pipeline should be called prior to unstash name: "stash-pf-config", to avoid git "not an empty directory" error
            if (isUnix() == true) {
                unstash name: "stash-pf-framework"
            }
            else {
                print "git clone (workaround)"
                if (env.PF_DEBUG_RESTARTABLE) {
                    bat """
                    set GIT_SSL_NO_VERIFY=true && git clone ${PF_FRAMEWORK_URL}/gerrit/sdlc/jenkins-pipeline --depth 1 -b ${PF_FRAMEWORK_DEV_BRANCH} .
                    """
                }
                else {
                    bat """
                    set GIT_SSL_NO_VERIFY=true && git clone ${PF_FRAMEWORK_URL}/gerrit/sdlc/jenkins-pipeline --depth 1 -b ${PF_FRAMEWORK_PROD_BRANCH} .
                    """
                }
            }
            print "unstash stash-pf-framework finished"
            unstash name: "stash-pf-config"
            print "unstash stash-pf-config finished"
        }
    }
}

def pascCleanWs() {
    if (isUnix() == true) {
        def whoami = sh(script: "whoami", returnStdout: true).trim()
        if (whoami == "root") {
            error("Do not run jenkins agent as root")
        }
    }

    if (env.PF_CLEAN_WS == "false") {
        print "pascCleanWs: skip"
        return
    }
    def excludes = [[pattern: "${env.PF_ROOT}/**", type: "EXCLUDE"]]
    if (env.PF_PRESERVE_SOURCE == "true") {
        if (env.PF_SOURCE_DSTS) {
            def scmDsts = env.PF_SOURCE_DSTS.split(",")
            for (def j=0; j<scmDsts.size(); j++) {
                def exclude = [:]
                exclude.pattern = "${scmDsts[j]}/**"
                exclude.type = "EXCLUDE"
                excludes << exclude
            }
        }
    }
    print "pascCleanWs: clean WS, excludes: " + excludes
    cleanWs deleteDirs: true, \
            notFailBuild: true, \
            patterns: excludes, \
            externalDelete: 'rm -rf *'  // More efficient than default
}

pipeline {
    // don't use 'agent any'
    // 'agent none' allows the job to continue on the same node with the same files
    agent ${AGENT_DESC}

    ${JENKINSFILE_OPTIONS}

    ${JENKINSFILE_TRIGGERS}

    stages {
        stage("PF-init") {
            steps {
                script {
                    pfInit(true)
                }
            }
        }
${JENKINSFILE_STAGES}
    }
    /*
    post {
        always {
            script {
                pf.preparePostStage()
                dir (env.PF_ROOT) {
                    dir ("scripts") {
                        def hasLogParserRule = fileExists 'logParserRule'
                        if (hasLogParserRule) {
                            logParser failBuildOnError: true, showGraphs:true, unstableOnWarning: true, useProjectRule: true, projectRulePath: 'logParserRule'
                        }
                    }
                }
                pf.postStage("always")
            }
        }
        success {
            script {
                pf.postStage("success")
	        }
        }
        failure {
            script {
                pf.postStage("failure")
            }
        }
        unstable {
            script {
                pf.postStage("unstable")
            }
        }
        changed {
            script {
                pf.postStage("changed")
            }
        }
    }
    */
}