VERSION 0.7
FROM alpine:3.17.3
WORKDIR /earthly-debug

docker:
    #ARG ssh_pub_key

    # create user SSH configuration
    RUN mkdir -p /root/.ssh \
        # only this user should be able to read this folder (it may contain private keys)
        && chmod 0700 /root/.ssh 
        # unlock the user
        #&& passwd -u root
        # supply your pub key via `--build-arg ssh_pub_key="$(cat ~/.ssh/id_rsa.pub)"` when running `docker build`
        #&& echo "$ssh_pub_key" > /root/.ssh/authorized_keys
    RUN apk add --update --no-cache openssh

    # ssh setting
    RUN mkdir /var/run/sshd
    RUN ssh-keygen -A
    RUN echo 'root:screencast' | chpasswd 
    RUN sed -i "s/#Port.*/Port 22/" /etc/ssh/sshd_config && \
        sed -i "s/#PermitRootLogin.*/PermitRootLogin yes/" /etc/ssh/sshd_config && \
        sed -i "s/#PasswordAuthentication.*/PasswordAuthentication yes/" /etc/ssh/sshd_config

    # expose the port 22(which is the default port of ssh)
    EXPOSE 22
    
    COPY * .
    CMD ["/usr/sbin/sshd", "-D"]
    SAVE IMAGE earthly-debug:latest

# usage
# docker run -p 2222:22 --rm -it earthly-debug
# ssh -o UserKnownHostsFile=/dev/null root@localhost -p 2222